name: Build Fireball Analyser
#env:
#  AWS_REGION: eu-west-2
#permissions:
#  id-token: write
#  contents: read

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
jobs:
  local_tests:
    name: local test stage
    runs-on: windows-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v4
      - name: testing
        run: |
          pip install -r requirements.txt
          pytest -v ./tests --cov=. --cov-report=term-missing
  build_fbtool:
    name: build fbcollector
    runs-on: windows-latest
    needs: local_tests
    steps:
      - name: building
        run: |
          echo "running build step"
          pip install -r requirements.txt
          pyinstaller ./fireballCollector.py --onefile --windowed --icon .\ukmda.ico
          markdown2 ./README.md > README.html
  package_fbtool:
    name: package fbcollector
    runs-on: windows-latest
    needs:
      - build_fbtool
    steps:
      - name: packaging
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: .\fireballcollector_setup.iss
  release_fbtool:
    name: release fbcollector
    runs-on: windows-latest
    needs:
      - package_fbtool
    steps:
      - name: release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.UKMDA_MM_PAT }}
        with:
          file: .\setup_fireballCollector.exe
          tags: true
          #draft: true
          overwrite: true
          tag_name: 2026.6.1
          # default_release_name: Tool to Gather Fireball data 
          default_release_body_path: ./release_notes.txt
#  cleanup_fbtool:
#    name: clean up temp fbcollector files
#    runs-on: windows-latest
#    continue-on-error: true
#    needs:
#      - release_fbtool
#    steps:
#      - name: delete package
#        run: |
#          del .\setup_fireballCollector.exe
